### ISSUE TITLE
className attribute not using the camel case notation

### ISSUE THREAD

**Issue by colis** [AEWP/php-block-builders#19]
There are instances where the `className` attribute is not using the `camelCase` notation, so we get two separate attributes in the markup: `classname` and `className`

These are the files that seem to be affected

![Screenshot 2023-02-09 at 15 03 59](https://user-images.githubusercontent.com/9059716/217842012-6f909358-d01f-4947-bafb-187306bfff81.png)

**Comment by john-jeeves-americaneagle** [comment]
Fixed by https://github.com/AEWP/php-block-builders/pull/20
